import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = process.env.NEXT_SKIP_GOOGLE_FONTS !== "true" ? 
  Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
  }) : null;

const geistMono = process.env.NEXT_SKIP_GOOGLE_FONTS !== "true" ? 
  Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
  }) : null;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans?.variable || ""} ${geistMono?.variable || ""} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
